name: Frontend CI/CD

on:
  push:
    branches: [ "main", "dev", "feature/*" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ "main", "dev", "feature/*" ]
    paths:
      - 'frontend/**'

env:
  APP_LOCATION: "frontend/InsuranceQuotes.UI" # location of your client code
  OUTPUT_LOCATION: "build"                    # location of client build output

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-static-web-app.outputs.static_web_app_url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_LOCATION }}/package-lock.json

      - name: Clean npm cache
        run: npm cache clean --force
        working-directory: ${{ env.APP_LOCATION }}

      - name: Install dependencies
        run: |
          npm install
          npm audit fix
        working-directory: ${{ env.APP_LOCATION }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.APP_LOCATION }}

      - name: Deploy to Azure Static Web Apps
        id: deploy-static-web-app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          skip_app_build: true # We already built the app in previous step